petstagram/common/urls.py
from django.urls import path

from petstagram.common import views

urlpatterns = [
    path('', views.index, name='index'),
    path('pet_photo_like/<int:pk>/', views.like_pet_photo, name='like_pet_photo'),
]

petstagram/pets/urls.py
from django.urls import path, include

from petstagram.pets import views

urlpatterns = [
    path('add/', views.PetCreateView.as_view(), name='add pet'),
    path('<str:username>/pet/<slug:pet_slug>/',
         include([
                path('', views.PetDetailView.as_view(), name='details pet'),
                path('edit/', views.PetEditView.as_view(), name='edit pet'),
                path('delete/', views.PetDeleteView.as_view(), name='delete pet'),

        ])),
]

petstagram/accounts/models.py
from django.db import models

# Create your models here.

petstagram/common/models.py
from django.db import models

from petstagram.photos.models import Photo


class PhotoComment(models.Model):
    MAX_TEXT_LENGTH = 300

    text = models.TextField(max_length=MAX_TEXT_LENGTH)
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)
    pet_photo = models.ForeignKey(Photo, on_delete=models.DO_NOTHING)


class PhotoLike(models.Model):
    pet_photo = models.ForeignKey(Photo, on_delete=models.DO_NOTHING)

petstagram/pets/models.py
from django.db import models
from django.utils.text import slugify


class Pet(models.Model):
    MAX_NAME_LENGTH = 30

    name = models.CharField(max_length=MAX_NAME_LENGTH, null=False, blank=False)
    pet_photo = models.URLField(null=False, blank=False)
    date_of_birth = models.DateField(null=True, blank=True)
    slug = models.SlugField(unique=True, null=False, blank=True, editable=False)

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        if not self.slug:
            self.slug = slugify(f'{self.name}-{self.id}')
        return super().save(*args, **kwargs)

petstagram/pets/forms.py
from django.core.exceptions import ValidationError
from django.forms import ModelForm
from django import forms

from petstagram.pets.models import Pet


class PetForm(ModelForm):
    class Meta:
        model = Pet
        fields = ('name', 'date_of_birth', 'pet_photo')

        widgets = {
            'name': forms.TextInput(attrs={'placeholder': 'Pet name'}),
            'date_of_birth': forms.DateInput(attrs={'type': 'date'}),
            'pet_photo': forms.URLInput(attrs={'placeholder': 'Link to image'}),

        }

        labels = {
            'name': 'Pet name',
            'pet_photo': 'Link to image'
        }


class PetCreateForm(PetForm):
    pass


class ReadonlyFieldsFormMixin:
    readonly_fields = ()

    def _apply_readonly_on_fields(self):
        for field_name in self.readonly_field_names:
            self.fields[field_name].widget.attrs['readonly'] = 'readonly'

    @property
    def readonly_field_names(self):
        if self.readonly_fields == '__all__':
            return self.fields.keys()
        return self.readonly_fields


class PetEditForm(PetForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['date_of_birth'].widget.attrs['readonly'] = 'readonly'

    def clean_date_of_birth(self):
        date_of_birth = self.cleaned_data.get('date_of_birth')
        if date_of_birth != self.instance.date_of_birth:
            raise ValidationError('Date of birth is readonly!')

        return self.instance.date_of_birth


class PetDeleteForm(ReadonlyFieldsFormMixin, PetForm):
    readonly_fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._apply_readonly_on_fields()

    def save(self, commit=True):
        if commit:
            self.instance.delete()
        return self.instance

petstagram/common/views.py
from django.shortcuts import render, redirect

from petstagram.common.models import PhotoLike
from petstagram.photos.models import Photo


def index(request):
    pet_name_pattern = request.GET.get('pet_name_pattern', None)

    photos = Photo.objects.all()

    if pet_name_pattern:
        photos = photos.filter(pets__name__icontains=pet_name_pattern)

    context = {
        'pet_photos': photos,
        'pet_name_pattern': pet_name_pattern
    }

    return render(request, 'common/home-page.html', context)


def like_pet_photo(request, pk):
    # pet_photo = PhotoLike.objects.get(pk=pk, user=request.user)
    pet_photo = PhotoLike.objects.filter(pet_photo_id=pk).first()

    if pet_photo:
        pet_photo.delete()
    else:
        PhotoLike.objects.create(pet_photo_id=pk)

    return redirect(request.META.get('HTTP_REFERER') + f'#photo-{pk}')

petstagram/pets/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, DetailView, UpdateView, DeleteView

from petstagram.pets.forms import PetForm, PetCreateForm, PetEditForm, PetDeleteForm
from petstagram.pets.models import Pet


class PetCreateView(CreateView):
    # model = Pet
    # fields = ('name', 'date_of_birth', 'pet_photo')
    form_class = PetCreateForm
    template_name = 'pets/pet-add-page.html'

    def get_success_url(self):
        return reverse('details pet', kwargs={
            'username': 'Svilen',
            'pet_slug': self.object.slug
        })


# def add_pet(request):
#     form = PetCreateForm(request.POST or None)
#
#     if request.method == 'POST':
#         if form.is_valid():
#             created_pet = form.save()
#             return redirect('details pet', username='Svilen', pet_slug=created_pet.slug)
#
#     context = {
#         'pet': form
#     }
#     return render(request, 'pets/pet-add-page.html', context)


class PetDetailView(DetailView):
    model = Pet   # object or pet in the template
    template_name = 'pets/pet-details-page.html'
    slug_url_kwarg = "pet_slug"

# def details_pet(request, username, pet_slug):
#     pet = Pet.objects.get(slug=pet_slug)
#
#     context = {
#         "pet": pet
#     }
#     return render(request, 'pets/pet-details-page.html', context)


class PetEditView(UpdateView):
    model = Pet
    form_class = PetEditForm
    template_name = 'pets/pet-edit-page.html'
    slug_url_kwarg = "pet_slug"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['username'] = 'Svilen'
        return context

    def get_success_url(self):
        return reverse('details pet', kwargs={
            'username': self.request.GET.get('username'),
            'pet_slug': self.object.slug,
        })


# def edit_pet(request, username, pet_slug):
#     pet = Pet.objects.filter(slug=pet_slug).get()
#     form = PetEditForm(request.POST or None, instance=pet)
#
#     if request.method == 'POST':
#         if form.is_valid():
#             form.save()
#             return redirect('details pet', username=username, pet_slug=pet_slug)
#
#     context = {
#         'form': form,
#         'username': username,
#         'pet': pet
#     }
#
#     return render(request, 'pets/pet-edit-page.html', context)


class PetDeleteView(DeleteView):
    model = Pet
    template_name = 'pets/pet-delete-page.html'
    form_class = PetDeleteForm
    slug_url_kwarg = 'pet_slug'

    def get_success_url(self):
        return reverse('index')

    extra_context = {
        'username': 'Svilen',
    }

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs["instance"] = self.object
        return kwargs

    # or this code to get data in the delete form
    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data(**kwargs)
    #
    #     form = self.form_class(instance=self.object)
    #     context['form'] = form
    #
    #     return context

# def delete_pet(request, username, pet_slug):
#     pet = Pet.objects.get(slug=pet_slug)
#     pet_form = PetDeleteForm(request.POST or None, instance=pet)
#
#     if request.method == 'POST':
#         pet_form.save()
#         return redirect('index')
#
#     context = {
#         'pet_form': pet_form,
#         'username': username,
#         'pet': pet
#     }
#     return render(request, 'pets/pet-delete-page.html', context)

templates/accounts/login-page.html
{% extends 'base.html' %}
{% load static %}

{% block main_content %}

    <div class="login-register-div">
        <div class="login-register-box">
            <h1>Petstagram</h1>

            <!-- Start Login Form-->
            <form action="#">
                <p>
                    <label for="id_username">Username:</label>
                    <input type="text" placeholder="Username">
                </p>
                <p>
                    <label for="id_password">Password:</label>
                    <input type="password" placeholder="Password">
                </p>

                <!-- Login Button-->
                <button type="submit">Log in</button>
            </form>
            <!-- End Login Form -->

        </div>
        <div class="second-option">

            <!-- Link to Register Page-->
            <p>Don't have an account? <a href="{% url 'register' %}">Register</a></p>
        </div>
    </div>

{% endblock %}

templates/accounts/profile-delete-page.html
{% extends 'base.html' %}
{% load static %}

{% block main_content %}

        <div class="delete-profile">
            <h1>
                Are you sure you want to delete your profile?
            </h1>
            <div class="sure-buttons">
                <!-- Yes (Delete Profile) Button -->
                <button>Yes</button>
                <!-- Go Back Button -->
                <a class="edit-btn" href="javascript:history.back()">Go Back</a>
            </div>
            <img src="/staticfiles/images/are_you_sure_cat.gif" alt="are you sure cat git">
        </div>
{% endblock %}


templates/accounts/profile-details-page.html
{% extends 'base.html' %}
{% load static %}

{% block main_content %}

      <div class="profile">
        <!-- Start Profile Personal Data Section -->
        <div class="profile-data">
          <div class="profile_img">
            <div class="image">
              <!-- Profile Image -->
              <img src="/staticfiles/images/person.png" alt="img8" />
            </div>
          </div>
          <div class="personal">
            <div class="edit">
              <!-- User Username -->
              <p>d_kalaydzhiev</p>

              <!-- IF the viewer is the owner of the profile -->
              <!-- Link to Edit Profile Page -->
              <a href="#">
                <img
                  class="edit-img"
                  src="/staticfiles/images/edit-pen-icon-6.jpg"
                  alt="edit button"
                />
              </a>

              <!-- Link to Delete Profile Page -->
              <a href="">
                <img
                  class="bin-img"
                  src="/staticfiles/images/icon-remove-22.jpg"
                  alt="bin button"
                />
              </a>
              <!-- End IF the viewer is the owner of the profile -->
            </div>
            <div class="data">
              <!-- Total Number of Photos by the User -->
              <span>4</span>
              <p>photos</p>

              <!-- Total Number of Pets owned by the User -->
              <span>7</span>
              <p>pets</p>

              <!-- Total Number of Likes for the User -->
              <span>436</span>
              <p>likes</p>
            </div>
            <!-- User First and Last Name IF Added -->
            <h3 class="names">Diyan Kalaydziev</h3>

            <!-- User Email Address -->
            <p class="email">d.denov@gmail.com</p>

            <!-- User Gender IF Added -->
            <p class="gender">Male</p>
          </div>
        </div>
        <!-- End Profile Personal Data Section -->

        <!-- Start Pets Data Section -->
        <div class="pets">
          <div class="statuses">
            <!-- Start 1st Pet Details Page -->
            <!-- Link to First Pet Details Page -->
            <a href="#">
              <div class="head-pet">
                <div class="status">
                  <div class="image">
                    <!-- Pet Image -->
                    <img
                      src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTgoIHq82qLYnvomfz5ZkW5CLQ8VNxCyI-hUw&usqp=CAU"
                      alt="pet img"
                    />
                  </div>
                </div>
                <!-- Pet Name -->
                <p>Sasho</p>
              </div>
            </a>
            <!-- End 1st Pet Details Page -->

            <!-- Start 2nd Pet Details Page -->
            <!-- Link to Second Pet Details Page -->
            <a href="#">
              <div class="head-pet">
                <div class="status">
                  <div class="image">
                    <!-- Pet Image -->
                    <img
                      src="https://cdn.pixabay.com/photo/2016/12/13/05/15/puppy-1903313__340.jpg"
                      alt="pet img"
                    />
                  </div>
                </div>
                <!-- Pet Name -->
                <p>Todi</p>
              </div>
            </a>
            <!-- End 2nd Pet Details Page -->

            <!-- Start 3rd Pet Details Page -->
            <!-- Link to Pet Details Page -->
            <a href="#">
              <div class="head-pet">
                <div class="status">
                  <div class="image">
                    <img
                      src="https://images.unsplash.com/photo-1611003228941-98852ba62227?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MXx8YmFieSUyMGRvZ3xlbnwwfHwwfHw%3D&w=1000&q=80"
                      alt="pet img"
                    />
                  </div>
                </div>
                <p>Mihail</p>
              </div>
            </a>
            <!-- End 3rd Pet Details Page -->

            <!-- Start 4th Pet Details Page -->
            <!-- Link to Pet Details Page -->
            <a href="#">
              <div class="head-pet">
                <div class="status">
                  <div class="image">
                    <img
                      src="https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/Cat03.jpg/1200px-Cat03.jpg"
                      alt="pet img"
                    />
                  </div>
                </div>
                <p>Petar</p>
              </div>
            </a>
            <!-- End 4th Pet Details Page -->

            <!-- Start 5th Pet Details Page -->
            <!-- Link to Pet Details Page -->
            <a href="#">
              <div class="head-pet">
                <div class="status">
                  <div class="image">
                    <img
                      src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQdKYe00NaD5SQjIMvXYPssq0r1dXJggL3ZIg&usqp=CAU"
                      alt="pet img"
                    />
                  </div>
                </div>
                <p>Stamat</p>
              </div>
            </a>
            <!-- End 5th Pet Details Page -->

            <!-- Start 6th Pet Details Page -->
            <!-- Link to Pet Details Page -->
            <a href="#">
              <div class="head-pet">
                <div class="status">
                  <div class="image">
                    <img
                      src="https://cf.ltkcdn.net/small-pets/images/orig/278587-1600x1066-goldfish-swimming-in-fish-tank.jpg"
                      alt="pet img"
                    />
                  </div>
                </div>
                <p>Toni</p>
              </div>
            </a>
            <!-- End 6th Pet Details Page -->

            <!-- Start 7th Pet Details Page -->
            <!-- Link to Pet Details Page -->
            <a href="#">
              <div class="head-pet">
                <div class="status">
                  <div class="image">
                    <img
                      src="https://i.pinimg.com/736x/01/6f/72/016f72c5812e1b8f71bdbf19d8c7558b.jpg"
                      alt="pet img"
                    />
                  </div>
                </div>
                <p>Daisy</p>
              </div>
            </a>
            <!-- End 7th Pet Details Page -->
          </div>
        </div>
        <!-- End Pets Data Section -->

        <!-- Start Last Uploaded Photos Section -->
        <div class="pet-photos">
          <!-- Link to Last Uploaded Pet Photo -->
          <a href="#">
            <!-- Pet Photo -->
            <img
              src="https://i.natgeofe.com/n/de94c416-6d23-45f5-9708-e8d56289268e/naturepl_01132178.jpg?w=636&h=631"
              alt="pet img"
            />
          </a>

          <!-- Link to Uploaded Pet Photo -->
          <a href="#">
            <!-- Pet Photo -->
            <img
              src="https://cf.ltkcdn.net/small-pets/images/orig/278587-1600x1066-goldfish-swimming-in-fish-tank.jpg"
              alt="pet img"
            />
          </a>

          <!-- Link to Uploaded Pet Photo -->
          <a href="#">
            <!-- Pet Photo -->
            <img
              src="https://thumbs.dreamstime.com/b/small-golden-retriever-puppy-6482030.jpg"
              alt="pet img"
            />
          </a>

          <!-- Link to  Uploaded Pet Photo -->
          <a href="#">
            <!-- Pet Photo -->
            <img
              src="https://i.pinimg.com/originals/4e/55/83/4e5583748bc4000805df50e4ebcafffc.png"
              alt="pet img"
            />
          </a>
        </div>
        <!-- End Last Uploaded Photos Section -->

        <!-- IF NO Posts Show No Post Image -->

        <img
          class="no-posts"
          src="/staticfiles/images/no_posts.png"
          alt="no posts"
        />
      </div>
{% endblock %}

templates/accounts/profile-edit-page.html
{% extends 'base.html' %}
{% load static %}

{% block main_content %}

    <div class="edit-delete">
        <h2>Edit Profile</h2>
        <!-- Start Edit Profile From -->
        <form action="">
            <div class="label-input">
                <label for="first name">First name: </label>
                <input type="text" placeholder="First name" value="Diyan">
            </div>
            <br>
            <div class="label-input">
                <label for="last name">Last name: </label>
                <input type="text" placeholder="Last name" value="Kalayadzhiev">
            </div>
            <br>
            <div class="label-input">
                <label for="username">Username: </label>
                <input type="text" placeholder="Username" value="k_dido">
            </div>
            <br>
            <div class="label-input">
                <label for="email">Email: </label>
                <input type="email" placeholder="Email" value="d.denov@gmail.com">
            </div>
            <br>
            <div class="label-input">
                <label for="image">Image: </label>
                <input type="text" placeholder="Link to to profile picture"
                       value="https://i.natgeofe.com/n/de94c416-6d23-45f5-9708-e8d56289268e/naturepl_01132178.jpg?w=636&h=631">
            </div>
            <br>

            <div class="label-input">
                <label for="image">Gender: </label>
                <div class="list-choice">
                    <div class="list-choice-title">Gender</div>
                    <div class="list-choice-objects">
                        <label>
                            <input type="radio" name="gender"/> <span>Male</span>
                        </label>
                        <label>
                            <input type="radio" name="gender"/> <span>Female</span>
                        </label>
                        <label>
                            <input type="radio" name="gender"/> <span>Do not show</span>
                        </label>
                    </div>
                </div>
            </div>

            <!-- Edit Profile Button -->
            <button class="edit-btn" type="submit">Edit</button>
        </form>
        <!-- End Edit Profile Form -->

    </div>
{% endblock %}

templates/accounts/register-page.html
{% extends 'base.html' %}
{% load static %}

{% block main_content %}

    <div class="login-register-div">
        <div class="login-register-box">
            <h1>Petstagram</h1>

            <!-- Start Register Form -->
            <form action="">
                <input type="text" placeholder="Username">

                <input type="email" placeholder="Email">

                <input type="password" placeholder="Password">

                <input type="password" placeholder="Repeat Password">

                <!-- Register Button -->
                <button type="submit">Register</button>
            </form>
            <!-- End Register Form -->

        </div>
        <div class="second-option">

            <p>Have an account? <a href="{% url 'login user' %}">Log in</a></p>
        </div>
    </div>
{% endblock %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<!-- Starts Head Section -->
<head>
    <link rel="stylesheet" href="{% static '/css/styles.css' %}">
    <link rel="icon" type="image/x-icon" href="{% static 'images/free-30-instagram-stories-icons23_122570.png' %} ">
    <title>Petstagram</title>
</head>
<body>

{% include 'partials/layout/header.html' %}

<main>
    {% block main_content %}
    
    {% endblock %}
</main>

{% include 'partials/layout/footer.html' %}

</body>
</html>

templates/common/home-page.html
{% extends 'base.html' %}
{% load static %}

{% block main_content %}

<div class="container">
        <div class="col-9">

            <!-- Start Searchbar Form -->
            <form class="searchbar" action="{% url 'index' %}" method="get">
                <input type="text" name="pet_name_pattern" placeholder="Search by pet name..." value="{{ pet_name_pattern }}">
                
                <button>
                    <img src="/staticfiles/images/search.png" height="18" alt="img2">
                </button>
            </form>
            
            {% include 'partials/pet-photos-list.html' with photo_list=pet_photos %}

        </div>
</div>

{% endblock %}

templates/partials/layout/footer.html
{% load static %}

<div class="footer">
		<span class="footer-section">
			© 2024 SOFTUNI WORKSHOP FOR PYTHON WEB MODULE
		</span>
</div>

templates/partials/layout/header.html
{% load static %}

<header>
    <nav class="navbar">
        <div class="container">
            <div class="logo">
                <!-- Link to Home Page -->
                <a href="{% url 'index' %}">
                    <img width="50px" src="{% static 'images/free-30-instagram-stories-icons23_122570.png' %}" alt="img1">
                </a>
                <a class="home" href="{% url 'index' %}">
                    <i>Petstagram</i>
                </a>
            </div>

            <div class="nav-links">
                <ul class="nav-group">
                    <li class="nav-item">
                        <a href="{% url 'add pet' %}">
                            <i>Add Pet</i>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'add photo' %}">
                            <i>Add Photo</i>
                        </a>
                    </li>
                    {% if request.user.is_authenticated %}
                        <li class="nav-item">
                        <a href="{% url 'details user' pk=1 %}">
                            <i>Profile</i>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url  'logout' %}">
                            <i>Log out</i>
                        </a>
                    </li>
                        
                    {% else %}
                        <li class="nav-item">
                        <a href="{% url 'login user' %}">
                            <i>Login</i>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'register' %}">
                            <i>Register</i>
                        </a>
                    </li>
                    {% endif %}
                    
                </ul>
            </div>
        </div>
    </nav>
</header>

templates/partials/layout/pet_list_card.html
{% load static %}

<div class="card">
                <div class="top">
                    <div class="userDetails">
                        <a href="{% url 'details user' pk=1 %}">
                            <div class="profilepic">
                                <div class="profile_img">
                                    <div class="image">
                                        <img src="{% static 'images/person.png' %}" alt="img8">
                                    </div>
                                </div>
                            </div>
                        </a>
                        <h3>
                            <a href="{% url 'details user' pk=1 %}">
                                Diyan Kalaydzhiev
                            </a>
                            <br>
                            <span>{{ photo.location }}</span>
                        </h3>
                    </div>
                </div>
    
                <div class="imgBx" id="photo-{{ photo.pk }}">
                    <img src="{{ photo.photo.url }}" alt="{{ photo.description }}" class="cover">
                </div>
    
                <div class="bottom">
                    <div class="actionBtns">
                        <div class="left">
                            <!-- Start Like Button -->
                            <span class="heart">
                                <a href="{% url 'like_pet_photo' pk=photo.pk %}">
                                    {% if photo.photolike_set.count > 0 %}
                                    <i class="fa-solid fa-heart" style="color: #ed4040;"></i>
                                    {% else %}
                                    <i class="fa-regular fa-heart"></i>
                                    {% endif %}
                                </a>
                            </span>
                            <!-- End Like Button -->

                            <!-- Start Share Button -->
                            <a href="#">
                                <i class="fa-solid fa-share"></i>
                            </a>
                            <!-- End Share Button -->

                        </div>
                    </div>
                
                    <p class="likes">{{ photo.photolike_set.count }} likes</p>

                    {% for pet in photo.pets.all %}

                    <a href="{% url 'details pet' username='Svilen' pet_slug=pet.slug %}">
                        <p class="message">
                            <b>{{ pet.name }}</b>
                        </p>
                    </a>
                    {% endfor %}
                    
                    <a href="{% url 'details photo' pk=photo.pk %}">
                        <h4 class="details">See details</h4>
                    </a>

                    <h5 class="postTime">{{ photo.created_at|date:'d/m/Y' }}</h5>

                    
                    <div class="addComments">

                        
                        <form method="post" action="#">
                            <label for="id_body">Body:</label>
                            <textarea name="body" cols="40" rows="10" placeholder="Add comment..." maxlength="300"
                                      required="" id="id_body"></textarea>
                            <button type="submit">Post</button>
                        </form>
                        <!-- End Add Comments Form -->

                    </div>
                    <!-- End Add Comments Section -->

                </div>
            </div>

templates/partials/pet-photos-list.html
{% load static %}

{% if photo_list %}
{% for photo in photo_list %}

    {% include 'partials/layout/pet_list_card.html' with photo=photo %}
    
{% endfor %}

{% else %}

<img class="no-posts" src="{% static 'images/no_posts.png' %}" alt="no posts image">

{% endif %}

templates/pets/pet-add-page.html
{% extends 'base.html' %}
{% load static %}

{% block main_content %}

    <div class="edit-delete edit-photo">
        <h2>Add pet</h2>

        <!-- Start Add Pet Form -->
        <form action="{% url 'add pet' %}" method="post">
            {{ form.as_p }}
            
            {% csrf_token %}
        
        <button class="add-btn" type="submit">Add Pet</button>
        </form>

    </div>
{% endblock %}

templates/pets/pet-delete-page.html
{% extends 'base.html' %}
{% load static %}

{% block main_content %}

    <div class="edit-delete edit-photo">
        <h2>Delete pet</h2>
        <!-- Starts Delete Pet Form -->
        <form action="{% url 'delete pet' username=username pet_slug=object.slug%}" method="post">
            {{ form.as_p }}
            
            <button class="delete-btn" type="submit">Delete</button>
            <a class="btn btn-primary" href="javascript:history.back()">
                <button class="edit-btn" type="button">Go back</button>
            </a>
            {% csrf_token %}
        </form>
    </div>
{% endblock %}

templates/photos/photo-details-page.html
{% extends 'base.html' %}
{% load static %}

{% block main_content %}

    <div class="container">
        <div class="col-9">

                {% include 'partials/layout/pet_list_card.html' with photo=pet_photo %}

                <p class="pet-details">{{ pet_photo.description }}</p>
                <h5 class="postTime">{{ pet_photo.created_at }}</h5>

            
        <div class="comments">
            {% for comment in pet_photo.photocomment_set.all %}
            <div class="top">
                <div class="userDetails"›
                    ‹div class="comment-data"> 
                        <div class="profilepic">
                            <div class="profile_img">
                                <div>a class=" image">
                                    <img src="{% static 'images/person.png' g}" alt="img8">
                                </div>
                            </div>
                        </div>
                            <p>
                         
                                    <a href="{% url 'details user' pk=1 %}">Steven Ivanov</div>a>
                                    </a>
                                    - {{ comment.text }}
                            </p>
                        </div>
                        <span>
                            {{ comment.created_at }}
                        </span>
                    </div>
                </div>
            </div>
                {% endfor %}
        </div>
    
{% endblock %}